### ISSUE TITLE
نادیاری بەشێک لە ئایەتەکانی و کێشەی دارک مۆد

### ISSUE THREAD

**Issue by ariMrashid** [H4zh4n/TafseeriNoor#2]
لە کاتی خوێندنی قورئان بە شێوەی لیست لەم ئەپلیکەیشنە هەندێک جار لە دەستی چەپەوە پیتێک یان چەند پیتێک دەبردرێت یاخود دیار نیە، وە بە گۆڕینی حەجمی پیتەکە ئەم کێشەیە چەرەسەر دەبێت بەڵام ئەو کاتە ئایەتێکی دیکە هەمان شتی بە سەر دێت.

وە کێشەیەکی تر ئەوەیە کە هەندێک جار بە بێ هۆکار مۆد دەگۆڕێت بە دارک وە بەپێچەوانەوە بەبێ ئەوەی لەسەر ئۆتۆماتیک بێت، وە کاتێک ئەمە ڕودەدات هەندێک جار ئەبێتە هۆێ سەیڤ نەبونی کۆتا خوێندنەوەکان

**Comment by H4zh4n** [comment]
دەستت خۆش کاک ئاری گیان، عەزێتت کێشا.

سەبارەت بە کێشەی یەکەم،
زیاتر لە فۆنتی me_quran دروست ئەبێت، پێموایە کە قەبارەی پیتەکان بە هەڵە دیاری کرابێت لەو جۆرە فۆنتە خۆی و کۆتایی هەندێك لە پیتەکان گرنگی پێ نادرێت. کەمێک زیادتر بۆشایم بە دێڕی ئایەتەکان داوە پێموایە کە کەمێك چارەسەر بووە لە نوێكاری داهاتوو (ڕەنگە ناوی لێ بنێم 1.1.9) ئەگەر هەر مابوو و بەرچاوت کەوت ئاگادارم بکەوە سوپاست ئەکەم.

بۆ کێشەی دووهەمیش ئاگادار نیم و سودفەیم نەکردووە ڕاستی لە ئێستا نازانم هۆکاری بەهۆی چیەوەیە تا چارەسەری بکەم.

جارێ کێشەکە بە کراوەیی جێ ئەهێڵم لێرە بە حوکمی ئەوەی بێ چارەم، ببەخشن هههه
